# Generated by Django 5.0.2 on 2024-02-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesversioncontrol',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='notesversioncontrol',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
